# Generated by Django 4.1.2 on 2022-10-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[("usd", "USD"), ("clp", "CLP")],
                default="clp",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("en", "English"), ("es", "Spanish")],
                default="en",
                max_length=2,
                verbose_name="language",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="login_method",
            field=models.CharField(
                choices=[("email", "Email"), ("github", "Github")],
                default="email",
                max_length=50,
            ),
        ),
    ]
