# Generated by Django 4.1.1 on 2022-10-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
