# Generated by Django 4.1.2 on 2022-10-08 22:02

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_guests_alter_room_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('added_by', models.DateTimeField(auto_now_add=True)),
                ('url', embed_video.fields.EmbedVideoField()),
                ('file', models.FileField(upload_to='room_videos')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='rooms.room')),
            ],
            options={
                'ordering': ['-added_by'],
            },
        ),
    ]
