# Generated by Django 4.1.2 on 2022-10-09 00:59

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='room',
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=embed_video.fields.EmbedVideoField(default='https://www.youtube.com/watch?v=9bZkp7q19f0'),
        ),
    ]
