# Generated by Django 4.1.4 on 2023-01-11 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_delete_video_alter_amenity_name_alter_facility_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='room',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='room',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='room',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
