databases:
  - name: default
    databaseName: default
    user: root

services:
  - type: web
    name: default
    env: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: default
          property: connectionString
      - key:
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4